project:
  type: book
  output-dir: docs

book:
  title: "R Cookbook for the Casual Dabbler (3rd Edition)"
  author: "Charles Coverdale"
  date: today
  chapters:
    - index.qmd
    - part: "Visualisation"
      chapters:
        - 02-making-maps-beautiful.qmd
        - 03-charts.qmd
    - part: "Analysis"
      chapters:
        - 04-basic-modelling.qmd
        - 05-hypothesis-testing.qmd
        - 06-forecasting.qmd
    - part: "Working with Data"
      chapters:
        - 07-web-scraping.qmd
        - 08-text-mining.qmd
    - part: "Geospatial"
      chapters:
        - 09-geocoding.qmd
        - 10-drivetime-analysis.qmd
        - 11-raster-data.qmd
    - part: "Economic Data"
      chapters:
        - 12-ABS-economic-data.qmd
        - 13-Australian-election-data.qmd
        - 18-UK-economic-data.qmd
    - part: "Advanced Topics"
      chapters:
        - 14-Bayesian-for-the-common-man.qmd
        - 15-causal-inference.qmd
        - 16-functions.qmd
        - 17-packages.qmd
  sidebar:
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/charlescoverdale/
      - icon: github
        href: https://github.com/charlescoverdale/casualdabbler3e

execute:
  cache: true

format:
  html:
    theme: cosmo
    bibliography: book.bib
    css: style.css
    toc: true
    toc-depth: 2
    number-sections: false
